Add oclif readme command
salesforcecli/github-workflows pull request #68
Opened 2023-09-11 20:49 UTC by iowillhoit

Adds `oclif readme` to the `create-github-release` step. 

We use [TriPSs/conventional-changelog-action](https://github.com/TriPSs/conventional-changelog-action) to bump versions and build changelogs. We can run this without any changes/commits/pushes and just get next the "next version" in the output. We then can pass that to `oclif readme` with `OCLIF_NEXT_VERSION`. 

Then we run the conventional-changelog-action again to generate and commit everything (including the readme changes)

Notes:
- I remove the `v` in the [source links](https://github.com/oclif/oclif/blob/main/src/commands/readme.ts#L206) using `sed`. We could make a flag for `oclif readme` if we wanted to 🤷 
- We discussed adding a `"readme": "oclif readme"` script to the `package.json` and adding that to wireit's `build` but we would have to update every single repo. 
- TripPSs does allow you to add a `pre-commit` scripts. Unfortunately it has to be a javascript file so we would also need to add a script to every repo.

Proof of this working: 
https://github.com/salesforcecli/plugin-info/actions/runs/6151426819/job/16691447475
Note the `Before git commands` and `After git commands` steps that I used to confirm changes.

2023-09-11 21:15 UTC, mdonnalley requested changes
Changes look good. Only blocking request is to make add a flag to `oclif readme` so we don't have to `sed` the README

2023-09-11 21:15 UTC, mdonnalley commented on .github/workflows/create-github-release.yml
> +          # oclif readme has the "v" tag prefix hardcoded, this will replace it with what is in the package.json (v or not)
I think this would be nice to have in `oclif readme` as a flag. Maybe `--[no-]version-prefix` or something like that. Or maybe it'd be `--repository-prefix` and you'd pass in `'<%- repo %>/blob/<%- version %>/<%- commandPath %>'`. I think I like that better because it'd mirror the existing behavior of being able to set that prefix in the package.json (https://github.com/oclif/oclif/blob/main/src/commands/readme.ts#L206)

2023-09-11 21:15 UTC, mdonnalley commented on .github/workflows/create-github-release.yml
> +          # oclif readme has the "v" tag prefix hardcoded, this will replace it with what is in the package.json (v or not)
One other thought: Our template repo has a `version` script in it that runs `oclif readme`, https://github.com/salesforcecli/plugin-template-sf/blob/main/package.json#L100

Which used to be run from plugin-release-management (https://github.com/salesforcecli/plugin-release-management/blob/bf2ebedb2750b7a6897c328d33a213ff820fe7a8/src/repository.ts#L185-L188) but doesn't look like it's being used anywhere now

But I'm assuming that even though most plugins will have a `version` script, we'd still have to touch every repo to add that as apart of the `wireit` config?

2023-09-11 21:15 UTC, mdonnalley commented on .github/workflows/create-github-release.yml
> +          OCLIF_NEXT_VERSION=${{ steps.next-version.outputs.tag }} npx oclif readme --no-aliases
I would use `yarn oclif readme` here instead of `npx` - just to make sure that the plugin is using the version that's specified in the package.json. It likely won't matter but I could imagine a scenario where we introduce a breaking change and we don't want plugins to have it until we're ready

2023-09-13 15:54 UTC, iowillhoit commented on .github/workflows/create-github-release.yml
> +          # oclif readme has the "v" tag prefix hardcoded, this will replace it with what is in the package.json (v or not)
We can't use `yarn version` because that will actually bump the version in the package.json. It's a built in yarn command and we (used to?) chain off of it. That is why we were considered adding `"readme": "oclif readme"` to the `package.json`. Then we would add this to the wireit `build` dependencies ([example](https://github.com/salesforcecli/plugin-info/blob/main/package.json#L132-L133)). 

A few downsides I saw with that approach: 
- I didn't want to update all repos (even with dev-scripts)
- Our pre-commit hook only runs a `lint`, so an updated readme is not guaranteed to be committed with a change
- Since conventional-commits bumps the version just before release, the versions in readme that we would build locally could be wrong (linking to a version that was already published)
- Our PRs would be noisier. No need to include readme changes in all our PRs.

I would much rather update the readme right before release (with GHA).

2023-09-13 15:55 UTC, iowillhoit commented on .github/workflows/create-github-release.yml
> +          # oclif readme has the "v" tag prefix hardcoded, this will replace it with what is in the package.json (v or not)
How would you feel about using `OCLIF_REPOSITORY_PREFIX` instead of a flag? Similar to `OCLIF_NEXT_VERSION` [here](https://github.com/oclif/oclif/blob/main/src/commands/readme.ts#L203).

2023-09-13 19:11 UTC, mdonnalley approved these changes

2023-09-13 19:29 UTC, iowillhoit commented
The warning works as expected. Will now bump `oclif` and run again
<img width="480" alt="Screenshot 2023-09-13 at 2 27 54 PM" src="https://github.com/salesforcecli/github-workflows/assets/1715111/f749b673-1dd1-4b15-b8c7-99f3f3084a5a">

2023-09-13 19:50 UTC, iowillhoit commented
Readme is getting created with the oclif changes ([here](https://github.com/salesforcecli/plugin-info/actions/runs/6176984329/job/16767119563#step:7:36))
Release: https://github.com/salesforcecli/plugin-info/releases/tag/2.6.42-dev.6

I downloaded the tarball and confirmed that README links were correct:
<img width="847" alt="Screenshot 2023-09-13 at 2 50 15 PM" src="https://github.com/salesforcecli/github-workflows/assets/1715111/ba49387c-e990-4e69-a45c-fb29983ea95f">

https://github.com/salesforcecli/plugin-info/blob/2.6.42-dev.6/src/commands/doctor.ts

2023-09-13 20:03 UTC, merged