Prereleases semver
salesforcecli/github-workflows pull request #8
Opened 2022-10-17 13:16 UTC by mshanemc

uses https://github.com/salesforcecli/conventional-changelog-action/tree/prereleases

2022-10-17 13:29 UTC, peternhale requested changes

2022-10-17 13:29 UTC, peternhale commented on .github/actions/getPreReleaseTag/action.yml
> +        # handle both 1.1.1-beta.0 and 1.1.1-beta
@mshanemc this is also a valid prerelease version `1.1.1-0`. Should this be rejected? The above regexp will match on `0` as the tag.

2022-10-18 14:16 UTC, RodEsp requested changes

2022-10-18 14:16 UTC, RodEsp commented on .github/actions/getPreReleaseTag/action.yml
> +        regex: '.*(?=\.\d+)'
This will only work correctly with a particular pre-release identifier; it should find an appropriate tag for any valid identifier or, at the very least, error out if it can't find one.

[Using regex101.com](https://regex101.com/r/aes0r1/1) and the examples found in the [semver prerelease identifier spec](https://semver.org/#spec-item-9), you can see it doesn't work correctly for anything with a format that's not `<tag>.#`
![image](https://user-images.githubusercontent.com/1084688/196449890-58ddf767-6f5e-402e-b750-ec93776d4cbc.png)

2022-10-18 16:44 UTC, RodEsp approved these changes

2022-10-18 16:46 UTC, RodEsp commented on .github/actions/getPreReleaseTag/action.yml
> +        regex: '.*(?=\.\d+)'
This is addressed by https://github.com/salesforcecli/github-workflows/pull/8/commits/d4f89873f9bf1a8f7631de6ae76692f5c85cc1d8 because it'll cause the release process to error out if a tag isn't found by this action.

2022-10-18 19:18 UTC, merged